### PR TITLE
Update Epinio icon

### PR DESCRIPTION
**Pull request by enrichman**
So from what it is understood this is the icon we want to update:

image

### CODE REVIEW

**Comment by mmartin24** [comment]
After testing it seems it gets fully greyed out:

image image



Not sure if maybe is because of the extension type. Note that some extensions as the `Oracle Free` one also have the same issue.
Perhaps could work a `.png` with color?

**Review by andreas-kupries — APPROVED** [review]

**Comment by enrichman** [comment]
Thanks @lucbpz , I've tried again and it works also for me!

image

Since this was in Ubuntu @mmartin24 could you check again, to see if this is something Mac related, or if was due to an old version? Thanks!

**Comment by mmartin24** [comment]
> Thanks @lucbpz , I've tried again and it works also for me!
> 
> image
> 
> Since this was in Ubuntu @mmartin24 could you check again, to see if this is something Mac related, or if was due to an old version? Thanks!

@enrichman working well in Ubuntu 22 and Mac

image
image

**Comment by enrichman** [comment]
Since this seems to be fixed I'm going to merge!

**Pull request merged**
